### ISSUE TITLE
편의기능 추가

### ISSUE THREAD

**Issue by Dylliss** [somnium-labs/smart-coin-support#1]
어플 잘 사용하고 있습니다. 감사합니다.
한가지 추가하면 좋을 것 같은 기능이 있어서 남깁니다.
시세 메뉴에서 코인을 즐겨찾기 하여 항상 상단에(필드별 정렬도 무시) 고정 해놓는 기능이 있으면 좋을 것 같습니다.

**Comment by east-shine** [comment]
@Dylliss  네 다음이나 다다음 버전에 추가해 볼게요. 일단 빠른 출시가 목표여서 일부 기능들이 빠졌네요 ^^; 의견 감사합니다.

**Comment by east-shine** [comment]
1.0.2 버전에 해당 기능 추가되어 이슈 클로즈 합니다.
